import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {buildEvidenceBundle} from '../tools/generate-layout/source-intake.mjs';
import {normalizeArtifact} from '../tools/generate-layout/normalize-source.mjs';
import {validateAIOutput} from '../tools/generate-layout/validate-ai-output.mjs';
import {mockProvider} from '../tools/generate-layout/providers/mock.mjs';
import {generateBatch, generateStore} from '../tools/generate-layout/index.mjs';
import {evaluateAgainstGolden, loadGoldenLayout} from '../tools/generate-layout/golden-evaluator.mjs';
import {validateLayout} from '../tools/layout-validator.mjs';
import {fixture, vision} from './ai-layout-fixture.mjs';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'floor777-goal5-'));
try {
  const input = path.join(root, 'input'), output = path.join(root, 'drafts');
  const manifest = await fixture(input);
  const evidence = await buildEvidenceBundle(manifest, {baseDir: input});
  assert.equal(evidence.sources.length, 3);
  assert.equal(evidence.sources[0].format, 'png');
  assert.equal(evidence.sources[1].structuredFacts.seats[0].number, 101);
  assert.equal(evidence.sources[0].contentHash.length, 64);
  assert(!JSON.stringify(evidence.sources[0].structuredFacts).includes('floor.png'));
  assert.equal(normalizeArtifact('x.jpg', Buffer.from([255, 216, 255, 217])).format, 'jpeg');
  assert.equal(normalizeArtifact('x.pdf', Buffer.from('%PDF-1.7')).format, 'pdf');
  assert.throws(() => normalizeArtifact('x.png', Buffer.from('not an image')));
  assert.equal(validateAIOutput(vision()).valid, true);
  assert.equal(validateAIOutput({...vision(), html: '<script>x</script>'}).valid, false);
  assert.equal(validateAIOutput({...vision(), floors: [{...vision().floors[0], width: -1}]}).valid, false);
  const duplicateRefs = structuredClone(vision()); duplicateRefs.floors[0].islands[0].sourceIds = ['map', 'map'];
  assert.equal(validateAIOutput(duplicateRefs).valid, false);
  let calls = 0;
  const provider = {...mockProvider, async generateLayoutFromEvidence(bundle) {calls++; return mockProvider.generateLayoutFromEvidence(bundle);}};
  const first = await generateStore(manifest, {baseDir: input, draftRoot: output, provider});
  assert.equal(first.status, 'generated');
  assert.equal(first.cached, false);
  assert.equal(first.layout.generation.source, 'ai');
  assert.equal(first.layout.verification.status, 'generated');
  assert.equal(first.layout.floors[0].islands[0].machines[0].machineName, '機種A');
  assert.equal(first.audit.confidenceFactors.sourceAgreement, null); // one roster cannot corroborate itself
  assert(first.audit.confidenceFactors.visibleNumberAgreement > 0);
  assert(validateLayout(first.layout).valid);
  const publicJSON = await fs.readFile(first.layoutPath, 'utf8');
  assert(!publicJSON.includes(input) && !publicJSON.includes('localArtifactPath') && !publicJSON.includes('data:image'));
  assert(first.layoutPath.includes('drafts') && !first.layoutPath.includes('data\\layouts'));
  const second = await generateStore(manifest, {baseDir: input, draftRoot: output, provider});
  assert(second.cached && calls === 1);
  const changedVersion = await generateStore(manifest, {baseDir: input, draftRoot: output, provider, generatorVersion: 'goal5-v2'});
  assert(!changedVersion.cached && calls === 2);
  const noMap = structuredClone(manifest); noMap.sources.shift();
  assert.equal((await generateStore(noMap, {baseDir: input, draftRoot: output})).status, 'insufficient_evidence');
  const badRental = structuredClone(manifest); badRental.sources[1].rentalType = '5枚';
  assert.equal((await generateStore(badRental, {baseDir: input, draftRoot: output})).status, 'blocked');
  const lowQuality = structuredClone(manifest); lowQuality.sources[0].structuredFacts.imageQuality = 0.1;
  assert.equal((await generateStore(lowQuality, {baseDir: input, draftRoot: output})).status, 'blocked');
  const incomplete = structuredClone(vision()); incomplete.floors[0].islands[0].machineSlots[1].visibleNumber = null;
  await fs.writeFile(path.join(input, 'vision.json'), JSON.stringify({visionOutput: incomplete}));
  const review = await generateStore(manifest, {baseDir: input, draftRoot: output});
  assert.equal(review.status, 'needs_review');
  assert.equal(review.layout.floors[0].islands[0].machines[1].number, null);
  assert(review.audit.validationSummary.codes.includes('reference_number_missing'));
  const invalid = structuredClone(vision()); invalid.floors[0].islands[0].machineSlots[0].position = [-1, 10, 20, 20];
  await fs.writeFile(path.join(input, 'vision.json'), JSON.stringify({visionOutput: invalid}));
  assert.equal((await generateStore(manifest, {baseDir: input, draftRoot: output})).status, 'blocked');
  const malformed = {...vision(), javascript: 'alert(1)'};
  await fs.writeFile(path.join(input, 'vision.json'), JSON.stringify({visionOutput: malformed}));
  assert.equal((await generateStore(manifest, {baseDir: input, draftRoot: output})).status, 'blocked');
  await fs.writeFile(path.join(input, 'vision.json'), JSON.stringify({visionOutput: vision()}));
  const broken = structuredClone(manifest); broken.storeId = 'missing-file'; broken.sources[0].localArtifactPath = 'absent.png';
  const batch = await generateBatch([manifest, broken], {baseDir: input, draftRoot: output});
  assert.equal(batch.counts.generated, 1); assert.equal(batch.counts.failed, 1);
  assert.equal(batch.results.length, 2);
  const {layout: golden} = loadGoldenLayout('hyper-arrow-mihara');
  const baseline = evaluateAgainstGolden(golden);
  assert.equal(baseline.seatCountDifference, 0);
  assert.deepEqual(baseline.missingNumbers, []);
  assert.equal(baseline.exactPositions, baseline.goldenSeatCount);
  assert.equal(baseline.goldenIslandCount, null);
  const shifted = structuredClone(golden); shifted.floors[0].unassignedMachines[0].position[0] += 10;
  const difference = evaluateAgainstGolden(shifted);
  assert(difference.meanCoordinateDistance > 0);
  assert.equal(difference.exactPositions, difference.goldenSeatCount - 1);
  await assert.rejects(() => generateStore(manifest, {baseDir: input, draftRoot: path.resolve('data/layouts')}),
    /cannot be written/);
  console.log('PASS: evidence normalization, AI schema, mock provider, reconciliation, confidence, blocked/review, drafts, batch, cache/version, Golden evaluation');
} finally {await fs.rm(root, {recursive: true, force: true});}
