import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {newProject,makeIsland,points,resizeIsland,assign,validate,importProject,exportFiles,fromLegacy,copy} from '../tools/builder-model.mjs';
import {zipFiles} from '../tools/builder-zip.mjs';
import {detectIslands} from '../tools/builder-detect.mjs';
const p=newProject();Object.assign(p,{id:'test-hall',name:'テスト店舗',city:'堺市'});
const a=makeIsland({key:'a',name:'直線',count:5,x:100,y:100,confirmed:true}),b=makeIsland({key:'b',name:'斜め',count:3,x:100,y:300,angle:45,pitch:38,confirmed:true});p.islands=[a,b];
assert.equal(validate(p).missing,8);assert.throws(()=>exportFiles(p),/未入力/);
assign(p,'a',{start:101,count:5,skip:'104'});assert.deepEqual(a.numbers,[101,102,103,105,106]);
assert.throws(()=>assign(p,'b',{start:103,count:3}),/重複/);assert.deepEqual(b.numbers,[]);
assign(p,'b',{start:201,count:3,reverse:true});assert.deepEqual(b.numbers,[203,202,201]);
assert.throws(()=>assign(p,'b',{start:201,count:2}),/台数/);
assign(p,'b',{count:3,explicit:'２０５,210-211'});assert.deepEqual(b.numbers,[205,210,211]);
assert.deepEqual(validate(p).errors,[]);const files=exportFiles(p);assert.equal(JSON.parse(files['data/test-hall.json']).seat_count,8);assert.equal(JSON.parse(files['registration.json']).status,'draft');assert(!('collector-entry.json' in files));
const restored=importProject(JSON.parse(JSON.stringify(p)));assert.deepEqual(restored.islands,p.islands);assert.notEqual(restored.key,p.key);
assert.throws(()=>importProject({...p,image:'data:image/svg+xml;base64,evil'}),/画像/);
assert.throws(()=>importProject({...p,islands:[a,a]}),/重複/);
assert.throws(()=>importProject({...p,islands:[{...a,count:Infinity}]}),/台数/);
const overlap=copy(p);overlap.islands[1].x=100;overlap.islands[1].y=100;assert(validate(overlap).errors.some(e=>e.includes('重な')));
const edge=copy(p);edge.islands[0].x=-1;assert(validate(edge).errors.some(e=>e.includes('範囲外')));
const circle=makeIsland({shape:'circle',count:4,x:300,y:300,radius:100,angle:0});assert.deepEqual(points(circle)[0],[388,288,24,24]);assert(Math.abs(points(circle)[3][1]-188)<.01);
const arc=makeIsland({shape:'arc',count:3,x:300,y:300,radius:100,angle:0,sweep:180});assert.equal(points(arc)[2][0],188);
const custom=makeIsland({shape:'custom',count:2,points:[[100,100,24,24],[131,122,24,24]],numbers:[]});assert.deepEqual(points(custom),custom.points);
const resized=copy(a);resizeIsland(resized,3);assert.equal(resized.count,3);assert.equal(resized.numbers.length,0);assert.equal(resized.confirmed,false);assert.equal(points(resized)[2][0],points(a)[4][0]);
const old=fromLegacy({id:'old',name:'旧店舗',prefecture:'大阪府',city:'堺市',minrepo_url:'',layout_date:'2026-09-20',rows:[{numbers:[10,11],x:200,y:300,direction:'left'}]});assert.deepEqual(points(old.islands[0])[1],[152,300,44,44]);
const bad=copy(p);bad.minrepo_url='https://min-repo.com.evil.example/tag/a';assert(validate(bad).errors.some(e=>e.includes('URL')));
const w=200,h=200,data=new Uint8ClampedArray(w*h*4);for(let y=20;y<180;y++)for(let x=30;x<45;x++){const k=(y*w+x)*4;data.set([20,120,220,255],k);}assert(detectIslands({width:w,height:h,data}).length>=1);
fs.writeFileSync(path.join(os.tmpdir(),'builder-export.zip'),Buffer.from(await zipFiles(files).arrayBuffer()));
fs.writeFileSync(path.join(os.tmpdir(),'builder-project.json'),JSON.stringify(p));
console.log('PASS: 25+ geometry, assignment, duplicates, validation, import, detection and export assertions');
