import assert from 'node:assert/strict';
import fs from 'node:fs';
import {ReviewSession, createIsland, findIsland, orderedMachines, copy} from '../tools/builder-model.mjs';
import {fromLegacyHall} from '../tools/layout-adapter.mjs';

const source = JSON.parse(fs.readFileSync('data/layouts/123-kitanoda.json', 'utf8'));
const original = copy(source);
const session = new ReviewSession(source);
const floor = session.layout.floors[0];
const islandId = floor.islands[0].id;
const first = () => findIsland(session.layout, islandId).island.machines[0].position;
const initial = [...first()];
assert.equal(session.layout.review.humanModified, false);
session.moveIsland(islandId, 12, 7);
assert.deepEqual(first().slice(0, 2), [initial[0] + 12, initial[1] + 7]);
assert.equal(session.layout.review.humanModified, true);
assert.equal(session.layout.verification.status, 'human_corrected');
assert(session.layout.review.modifiedAt);
session.undo(); assert.deepEqual(first(), initial);
session.redo(); assert.deepEqual(first().slice(0, 2), [initial[0] + 12, initial[1] + 7]);
session.undo();
session.rotateIsland(islandId, 1);
assert.equal(findIsland(session.layout, islandId).island.shape, 'custom');
assert.notDeepEqual(first(), initial);
session.undo(); assert.deepEqual(first(), initial);
session.scaleIsland(islandId, 1.2);
assert(first()[2] > initial[2]);
session.undo(); assert.deepEqual(first(), initial);
const beforeCount = findIsland(session.layout, islandId).island.machineCount;
session.setMachineCount(islandId, beforeCount + 2);
assert.equal(findIsland(session.layout, islandId).island.machines.length, beforeCount + 2);
assert.equal(findIsland(session.layout, islandId).island.machines.at(-1).number, null);
session.undo(); assert.equal(findIsland(session.layout, islandId).island.machineCount, beforeCount);
const beforeFailure = copy(session.layout);
assert.throws(() => session.setMachineCount(islandId, 0));
assert.deepEqual(session.layout, beforeFailure, 'failed edit must be atomic');
const addedId = session.addIsland(floor.id, {shape: 'arc', x: 600, y: 350, count: 4});
assert.equal(findIsland(session.layout, addedId).island.shape, 'arc');
session.deleteIsland(addedId);
assert(!session.layout.floors[0].islands.some(island => island.id === addedId));
session.undo(); assert.equal(findIsland(session.layout, addedId).island.machineCount, 4);
assert.deepEqual(source, original, 'source layout must not be mutated');

const hall = {id: 'review-test', name: 'Review test', seats: []};
const layout = fromLegacyHall(hall, {});
layout.floors[0].width = 1400;
layout.floors[0].height = 700;
const numbers = Array.from({length: 20}, (_, index) => 801 + index);
const fresh = new ReviewSession(layout, {referenceNumbers: numbers});
const created = fresh.addIsland('legacy-slot', {shape: 'line', x: 80, y: 80, count: 20});
const island = findIsland(fresh.layout, created).island;
assert.equal(orderedMachines(island, {direction: 'right-left'})[0].id, island.machines.at(-1).id);
fresh.assignSequential(created, {start: 801, count: 20, direction: 'left-right'});
assert.deepEqual(island.machines.map(machine => machine.number), numbers);
assert.equal(fresh.diagnostics.valid, true);
fresh.reverseNumbers(created);
assert.deepEqual(island.machines.map(machine => machine.number), numbers.slice().reverse());
fresh.undo();
assert.deepEqual(findIsland(fresh.layout, created).island.machines.map(machine => machine.number), numbers);
fresh.redo();
assert.deepEqual(findIsland(fresh.layout, created).island.machines.map(machine => machine.number), numbers.slice().reverse());
fresh.clearNumbers(created, [island.machines[0].id]);
assert(fresh.diagnostics.diagnostics.some(item => item.code === 'number_missing' && item.machineId === island.machines[0].id));
fresh.setMachineNumber(island.machines[0].id, island.machines[1].number);
assert(fresh.diagnostics.diagnostics.some(item => item.code === 'number_duplicate' && item.machineId));
fresh.undo(); fresh.undo(); fresh.undo(); // restore the complete 801–820 sequence
assert.deepEqual(findIsland(fresh.layout, created).island.machines.map(machine => machine.number), numbers);
fresh.verify();
assert.equal(fresh.layout.verification.status, 'verified');
fresh.moveIsland(created, 1, 0);
assert.equal(fresh.layout.verification.status, 'human_corrected');
assert.equal(fresh.layout.verification.lastVerifiedAt, null);
fresh.undo();
assert.equal(fresh.layout.verification.status, 'verified');
assert.equal(original.verification.status, 'needs_review');

const skipped = new ReviewSession(layout);
const skipId = skipped.addIsland('legacy-slot', {count: 5});
skipped.assignSequential(skipId, {start: 801, count: 5, exclude: [804]});
assert.deepEqual(findIsland(skipped.layout, skipId).island.machines.map(machine => machine.number), [801, 802, 803, 805, 806]);
assert.throws(() => skipped.assignSequential(skipId, {start: 801, count: 5, end: 802}));
console.log('PASS: v3 review geometry, count/add/delete, number direction/skip/reverse/clear, diagnostics, undo/redo, provenance and explicit verification');
